#!/usr/bin/env python

import argparse
from hawks import Hawks
from hawks_api import run_api

def parse_args():
  parser = argparse.ArgumentParser()
  parser.add_argument("--bgcolor", default="black")
  parser.add_argument("--outercolor", default="green")
  parser.add_argument("--innercolor", default="blue")
  parser.add_argument("--font", default="FreeSansBold")
  parser.add_argument("--x", type=int, default=0, help="left position of text")
  parser.add_argument("--y", type=int, default=2, help="top position of text")
  parser.add_argument("--rows", type=int, default=32)
  parser.add_argument("--cols", type=int, default=32)
  parser.add_argument("--text", default="12")
  parser.add_argument("--textsize", type=int, default=27)
  parser.add_argument("--thickness", type=int, default=1)
  parser.add_argument("--preset", default=None, choices=Hawks.PRESETS.keys())
  parser.add_argument("--port", type=int, default=1212)
  parser.add_argument("--debug", action="store_true", default=False)
  return parser.parse_args()
  return args

def main():
  args = parse_args()
  hawks_args = args._get_kwargs()
  hawks_args.pop("port")
  hawks = Hawks(hawks_args)
  run_api('', port, hawks)


if __name__ == '__main__':
  main()

